### ISSUE TITLE
Travis fail

### ISSUE THREAD

**Issue by alyssacaputo** [cisc3410/2-minimax#10]
@rivlev 
I updated the travis file to have tictactoe.cpp instead of main.cpp, but now I am getting these errors from Travis. It is referring to shuffle in the getEmptyvec() function. Did anyone else have this same issue?
![screen shot 2017-10-30 at 5 29 08 pm](https://user-images.githubusercontent.com/21319464/32196786-2f0cb7d2-bd98-11e7-829a-e470da7401e9.png)

**Comment by midwestmonika** [comment]
In TicTacToe.h, add the line `#include <algorithm>`

**Comment by alyssacaputo** [comment]
@monikaciecka thank you!
