### ISSUE TITLE
Problems submitting

### ISSUE THREAD

**Issue by MichaelGregg** [cisc3410/2-minimax#12]
I am having trouble submitting my project. this is what happens when i execute the git commit command:
![screen shot 2017-10-30 at 10 45 21 pm](https://user-images.githubusercontent.com/25493211/32206795-d5be91c4-bdcd-11e7-83bc-69eb71792124.png)
I then tried to do it again:
![screen shot 2017-10-30 at 10 46 36 pm](https://user-images.githubusercontent.com/25493211/32206797-dde4cabc-bdcd-11e7-9d92-eff957a7d232.png)
I then tried just "git push":
![screen shot 2017-10-30 at 10 48 30 pm](https://user-images.githubusercontent.com/25493211/32206799-e6079300-bdcd-11e7-9a65-599a31a04eb2.png)
I then tried git push origin hw again:
![screen shot 2017-10-30 at 10 50 22 pm](https://user-images.githubusercontent.com/25493211/32206802-edfe21a0-bdcd-11e7-9c33-de81da64502a.png)
I then tried git push again:
![screen shot 2017-10-30 at 10 51 40 pm](https://user-images.githubusercontent.com/25493211/32206809-f69065e4-bdcd-11e7-908a-a0648101a2d9.png)
I then tried to start over again:
![screen shot 2017-10-30 at 10 52 39 pm](https://user-images.githubusercontent.com/25493211/32206816-05bb94f8-bdce-11e7-8343-83695ba211b9.png)
I then tried git push again:
![screen shot 2017-10-30 at 10 53 20 pm](https://user-images.githubusercontent.com/25493211/32206823-11ff8a58-bdce-11e7-90cb-795c0bb46f08.png)

This is where i stopped because i thought my efforts are probably making it worse. I can see in the repository there is a commit, but i could not create a pull request. I did what i do every other time i turn in an assignment, why is it not working? and what should i do to fix it?

I also emailed you my assignment since this is not working.
@rivlev

**Comment by MichaelGregg** [comment]
When i do git push origin assignment:
![screen shot 2017-10-31 at 12 00 31 am](https://user-images.githubusercontent.com/25493211/32206905-a9483ed2-bdce-11e7-9aa2-8384060a069e.png)
Now what shows when i click base in the pull request page:
![screen shot 2017-10-31 at 12 03 48 am](https://user-images.githubusercontent.com/25493211/32206973-1e5964ee-bdcf-11e7-9805-05678afc584d.png)
Now what shows when i click compare in the pull request page 
![screen shot 2017-10-31 at 12 03 57 am](https://user-images.githubusercontent.com/25493211/32206978-231db7fa-bdcf-11e7-83c4-fc58017e96f0.png)
Should i select one of them to be "rivlev-patch-1" and keep the other at "assignment" and create a pull request?
@rivlev

**Comment by rivlev** [comment]
It looks like you did not create a hw branch and so it can't be pushed.
```git push``` worked and your assignment branch now has the commit pushed.
Since you did not create a clean hw branch, you have nothing to compare.

1. From your local repository, create a hw branch
   ```git checkout -b hw```

1. Make a small change to the hw branch
```touch dummy.txt```

1. ```git add dummy.txt```
   ```git commit -m "made dummy change"```
   ```git push origin hw```

1. checkout assignment branch
   ```git checkout assignment```

1. Revert it back to clean version
   ```git reset --hard ff0a06e331f47eab9ff73781536f9143a783b615```
   *Note: THIS DESTROYS ALL CHANGES YOU HAVE MADE -- first make sure they are saved and synced to github in the hw branch*

1. Create pull request comparing hw and assignment

**Comment by MichaelGregg** [comment]
@rivlev Thanks i think it worked now
