### ISSUE TITLE
Repo Not Available on Travis

### ISSUE THREAD

**Issue by myang310** [cisc3410/2-minimax#6]
Same problem as in HW #1. My Travis does not have my HW #2 repo connected to it. https://github.com/cisc3410/1-search/issues/6

I think you'll have to manually add again and I'll push a trivial change after the repo is added. Thanks.

**Comment by rivlev** [comment]
Try accessing it yourself by replacing the word "github" in your private repository's url with "travis-ci"
https://travis-ci.com/cisc3410/2-minimax-myang310
